#!/bin/sh

PLATFORM=$(uname -o 2>/dev/null || uname -s)

while getopts ":s:d:hl:" opt; do
	case $opt in
		d)
			case $PLATFORM in
				GNU/Linux|FreeBSD|DragonFly|NetBSD|OpenBSD)
					printf 'lib%s.so' "$OPTARG"
					;;
				Darwin)
					printf 'lib%s.dylib' "$OPTARG"
					;;
				Msys|Cygwin)
					printf '%s.dll' "$OPTARG"
					;;
				*)
					echo "unknown platform '$PLATFORM'" >&2
					exit 1
			esac
			;;
		s)
			case $PLATFORM in
				GNU/Linux|FreeBSD|DragonFly|NetBSD|OpenBSD|Darwin)
					printf 'lib%s.a' "$OPTARG"
					;;
				Msys|Cygwin)
					printf '%s.lib' "$OPTARG"
					;;
				*)
					echo "unknown platform '$PLATFORM'" >&2
					exit 1
			esac
			;;
		l)
			case $PLATFORM in
				GNU/Linux|FreeBSD|DragonFly|NetBSD|OpenBSD)
					printf -- '-shared -Wl,-soname -Wl,lib%s.so' "$OPTARG"
					;;
				Darwin)
					printf -- '-dynamiclib'
					;;
				Msys|Cygwin)
					printf -- ''
					;;
				*)
					echo "unknown platform '$PLATFORM'" >&2
					exit 1
			esac
			;;
		h)
			echo "Usage shared_lib [options]"
			echo "  -s [name]: static shared library name"
			echo "  -d [name]: dynamic shared library name"
			echo "  -l [name]: compiler argument for shared library called [name]"
			;;
		\?)
			echo "invalid argument '$OPTARG'" >&2
			exit 1
	esac
done
